load("//third_party/java:rules.bzl", "junit5_test")
load("//tools/java-format:defs.bzl", "PALANTIR_JVM_FLAGS")

package(default_visibility = ["//visibility:public"])

junit5_test(
    name = "javaformat_tests",
    srcs = [
        "PalantirFormatterTest.java",
        "PalantirJavaFormatMainTest.java",
        "PalantirJavaFormatWatcherTest.java",
        "PalantirJavaFormatWorkerMainTest.java",
        "package-info.java",
    ],
    jvm_flags = PALANTIR_JVM_FLAGS,
    test_package = "org.realityforge.jdbt.tools.javaformat",
    deps = [
        "//third_party/java:assertj_core",
        "//tools/java-format:com_palantir_javaformat__palantir_java_format",
        "//tools/java-format:com_palantir_javaformat__palantir_java_format_spi",
        "//tools/java-format/src/main/java/org/realityforge/jdbt/tools/javaformat",
        "//tools/java-format/src/main/java/org/realityforge/jdbt/tools/javaformat:watcher",
        "//tools/java-format/src/main/java/org/realityforge/jdbt/tools/javaformat:worker",
        "//tools/java-format/src/main/java/org/realityforge/jdbt/tools/javaformat:worker_protocol_java",
    ],
)
