load("@protobuf//bazel:java_proto_library.bzl", "java_proto_library")
load("//third_party/java:rules.bzl", "java_binary", "java_library")
load("//tools/java-format:defs.bzl", "PALANTIR_JVM_FLAGS")

package(default_visibility = [
    "//:__pkg__",
    "//tools/java-format:__subpackages__",
])

java_library(
    name = "javaformat",
    srcs = [
        "PalantirFormatter.java",
        "PalantirJavaFormatMain.java",
        "package-info.java",
    ],
    runtime_deps = ["//tools/java-format:com_palantir_javaformat__palantir_java_format"],
    deps = ["//tools/java-format:com_palantir_javaformat__palantir_java_format_spi"],
)

java_binary(
    name = "java_format",
    jvm_flags = PALANTIR_JVM_FLAGS,
    main_class = "org.realityforge.jdbt.tools.javaformat.PalantirJavaFormatMain",
    runtime_deps = [":javaformat"],
)

java_proto_library(
    name = "worker_protocol_java",
    deps = ["@bazel_tools//src/main/protobuf:worker_protocol_proto"],
)

java_library(
    name = "worker",
    srcs = ["PalantirJavaFormatWorkerMain.java"],
    deps = [
        ":javaformat",
        ":worker_protocol_java",
        "//tools/java-format:com_palantir_javaformat__palantir_java_format_spi",
    ],
)

java_binary(
    name = "palantir_java_format_worker",
    jvm_flags = PALANTIR_JVM_FLAGS,
    main_class = "org.realityforge.jdbt.tools.javaformat.PalantirJavaFormatWorkerMain",
    runtime_deps = [":worker"],
)
