load("//third_party/java:rules.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "db",
    srcs = ["DbDriverFactory.java"],
    exports = [":db_core"],
    deps = [
        ":db_core",
        "//src/main/java/org/realityforge/jdbt/config",
        "//src/main/java/org/realityforge/jdbt/db/sqlserver",
    ],
)

java_library(
    name = "db_core",
    srcs = [
        "DatabaseConnection.java",
        "DatabaseException.java",
        "DatabaseMetadata.java",
        "DbDriver.java",
        "ImportMaintenanceObserver.java",
        "NoOpDbDriver.java",
        "QueryResult.java",
        "SqlTimingObservation.java",
        "SqlTimingObserver.java",
        "package-info.java",
    ],
    deps = ["//src/main/java/org/realityforge/jdbt/config"],
)
