load("//third_party/java:rules.bzl", "junit5_test")

package(default_visibility = ["//visibility:public"])

junit5_test(
    name = "postgres_tests",
    srcs = [
        "PostgresDbDriverTest.java",
        "package-info.java",
    ],
    test_package = "org.realityforge.jdbt.db.postgres",
    deps = [
        "//src/main/java/org/realityforge/jdbt/db:db_core",
        "//src/main/java/org/realityforge/jdbt/db/postgres",
        "//third_party/java:assertj_core",
        "//third_party/java:mockito_core",
    ],
)
