load("@ahab//:defs.bzl", "ahab", "ahab_check", "ahab_explain", "ahab_update")

exports_files(["exceptions.json"])

REPRO_SPECS = [{
    "@rules_palantir_java_format//java_format/private/java/org/realityforge/rules/palantirjavaformat/palantir_java_format_worker": {
        "spec": {"reproducibility": "always"},
    },
}]

# Analyze and produce a visual report
ahab(
    name = "hermeticity",
    label = "//...",
    repro_specs = REPRO_SPECS,
)

# Ensure hermeticity has not been comprised except for explict exceptions
ahab_check(
    name = "hermeticity.check",
    baseline = "exceptions.json",
    label = "//...",
    repro_specs = REPRO_SPECS,
)

# Update the exception list
ahab_update(
    name = "hermeticity.update",
    baseline = "exceptions.json",
    label = "//...",
    repro_specs = REPRO_SPECS,
)

# Produces a report based on current exceptions in json
ahab_explain(
    name = "hermeticity.explain",
    report = "exceptions.json",
)
